version: '3.8'
services:
  app:
    build: 
      context: .
    ports:
      - "8000:80"
    container_name: translation_app
    restart: unless-stopped
    working_dir: /var/www/repo/translation-service
    volumes:
      - .:/var/www/repo/translation-service
    networks:
      - laravel_network
    depends_on:
      - mysql
    env_file:
      - .env
    command: php artisan serve --host=0.0.0.0 --port=80  # Add this line

  mysql:
    image: mysql:8
    container_name: translation_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: translation_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 5
      timeout: 5s

  redis:
    image: redis:alpine
    container_name: translation_redis
    restart: unless-stopped
    networks:
      - laravel_network
    ports:
      - "6380:6379"

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data: